service:
  property1: this is for default
  

  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monetary_db
    username: root
    password: Password@1_
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
   enabled: true
   base-url: http://localhost:9411/ #OK

  jpa:
    show-sql: true
 
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
      


 